
/**
 * SET IS LOADING PAGE
 */
export const SET_IS_LOADING_PAGE = "SET_IS_LOADING_PAGE";

/**
 * SET AUTH ERROR MESSAGE
 */
export const SET_AUTH_ERROR_MESSAGE = "SET_AUTH_ERROR_MESSAGE";

/**
 * INITIALIZE STATE FOR AUTH REQUEST 
 */
export const INIT_AUTH_REQ_STATE = "INIT_AUTH_REQ_STATE";

/**
 * AUTH CHANNEL
 */
export const AUTH_CHANNEL_REQUEST = "AUTH_CHANNEL_REQUEST";

/** 
 * SIGN UP
 * */ 
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";

/**
 * LOG IN
 */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";

/**
 * LOGOUT
 */
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";
