
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_LOADING_PAGE = "SET_IS_LOADING_PAGE";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

/**
 * AUTH CHANNEL
 */
export const AUTH_CHANNEL_REQUEST = "AUTH_CHANNEL_REQUEST";

/** 
 * SIGN UP
 * */ 
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";

/**
 * LOG IN
 */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";

/**
 * LOGOUT
 */
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";
