/**
 * INITIALIZE STATE FOR SERVICE REQUEST 
 */
export const INIT_SERVICE_REQ_STATE = "SET_SERVICE_REQ_INIT_STATE";

/** 
 * CREATE SERVICE
 * */ 
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_RESPONSE = "CREATE_SERVICE_RESPONSE";

/** 
 * SEARCH SERVICE
 * */ 
export const SEARCH_SERVICE_REQUEST = "SEARCH_SERVICE_REQUEST";
export const SEARCH_SERVICE_RESPONSE = "SEARCH_SERVICE_RESPONSE";

