
export const SET_IS_SERVICE_LOADING = "SET_IS_SERVICE_LOADING";
export const SET_SERVICE_ERROR_MESSAGE = "SET_SERVICE_ERROR_MESSAGE";

/** 
 * CREATE SERVICE
 * */ 
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_RESPONSE = "CREATE_SERVICE_RESPONSE";

