/**
 * INITIALIZE STATE FOR SERVICE REQUEST 
 */
export const INIT_SERVICE_REQ_STATE = "INIT_SERVICE_REQ_STATE";

/** 
 * CREATE SERVICE
 * */ 
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_RESPONSE = "CREATE_SERVICE_RESPONSE";

/** 
 * UPDATE SERVICE
 * */ 
export const UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST";
export const UPDATE_SERVICE_RESPONSE = "UPDATE_SERVICE_RESPONSE";

/** 
 * DELETE SERVICE
 * */ 
export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST";
export const DELETE_SERVICE_RESPONSE = "DELETE_SERVICE_RESPONSE";

/** 
 * GET SERVICE LIST
 * */ 
export const GET_SERVICE_LIST_REQUEST = "GET_SERVICE_LIST_REQUEST";
export const GET_SERVICE_LIST_RESPONSE = "GET_SERVICE_LIST_RESPONSE";

/** 
 * GET SERVICE BY ID
 * */ 
export const GET_SERVICE_BY_ID_REQUEST = "GET_SERVICE_BY_ID";
export const GET_SERVICE_BY_ID_RESPONSE = "GET_SERVICE_BY_ID_RESPONSE";


/** 
 * ADD REVIEW
 * */ 
export const ADD_SERVICE_REVIEW_REQUEST = "ADD_SERVICE_REVIEW_REQUEST";
export const ADD_SERVICE_REVIEW_RESPONSE = "ADD_SERVICE_REVIEW_RESPONSE";


/** 
 * SEARCH SERVICE
 * */ 
export const SEARCH_SERVICE_REQUEST = "SEARCH_SERVICE_REQUEST";


