/**
 * INITIALIZE STATE FOR USER REQUEST 
 */
export const INIT_USER_REQ_STATE = "INIT_USER_REQ_STATE";

/** 
 * UPDATE USER
 * */ 
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_RESPONSE = "UPDATE_USER_RESPONSE";

/** 
 * DELETE USER
 * */ 
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_RESPONSE = "DELETE_USER_RESPONSE";

/** 
 * GET USER LIST
 * */ 
export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const GET_USER_LIST_RESPONSE = "GET_USER_LIST_RESPONSE";